name: Playground Continuous Integration
on: [pull_request]

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  call-test-maven-jar:
    name: Run Automated Tests - Maven JAR
    uses: eclipse-pass/playground/.github/workflows/maven-jar-test.yml@main

  call-test-maven-service:
    name: Run Automated Tests - Maven service
    uses: eclipse-pass/playground/.github/workflows/maven-service-test.yml@main

  temp-call-publish-html-app:
    name: TEMP - Publish HTML app
    uses: eclipse-pass/playground/.github/workflows/html-app-publish.yml@090962cdbac05a04db8e32f6e1e076c7a86f6c3e
